spring:
  application:
    name: bank
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingdb
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  redis:
    host: localhost
    port: 6379
  
  security:
    user:
      name: admin
      password: admin123
    basic:
      enabled: false  

server:
  port: 8080

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
  
  fraud:
    threshold: 0.7
    large-amount-threshold: 10000

logging:
  level:
    com.banking.fraud: DEBUG
    org.springframework.security: DEBUG